### ISSUE TITLE
Paramiko args / compatibility with RouterOS 6.40.*

### ISSUE THREAD

**Issue by alryaz** [napalm-automation-community/napalm-ros#107]
### Description of Issue/Question
ROS 6.40.9 does not provide supported key algorithms when establishing SSH transport, so a key algo must be guessed. The algorithm chosen by Paramiko by default causes immediate connection loss.

It would be beneficial to implement an `optional_args`-based arguments pass-through to both the SSHClient instance and its `.connect(...)` method.

So far the issue had been fixed temporarily by providing a `disabled_algorithms` keyword argument, leaving only `ssh-rsa` as available algo; this is an unacceptable fix in the long run due to MikroTik straying away from `ssh-rsa` since 2020.

### napalm-ros version
(Paste verbatim output from `pip freeze | grep napalm-ros` between quotes below)

```
napalm-ros==1.2.2
```

### ROS version
(Paste verbatim output from `/system package print` between quotes below)

```
Flags: X - disabled
 #   NAME                     VERSION                     SCHEDULED
 0   routeros-mipsbe          6.40.9
 1   system                   6.40.9
 2 X ipv6                     6.40.9
 3   wireless                 6.40.9
 4   hotspot                  6.40.9
 5   dhcp                     6.40.9
 6   mpls                     6.40.9
 7   routing                  6.40.9
 8   ppp                      6.40.9
 9   security                 6.40.9
10   advanced-tools           6.40.9
```

### librouteros version
(Paste verbatim output from `pip freeze | grep librouteros` between quotes below)
```
librouteros==3.2.1
```

### python version
(paste output of python --version)
```

```

### Steps to Reproduce the Issue
0. Grab a CRS109
1. Up(Down)grade to 6.40.9
2. Execute `get_config`

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
# /var/log/syslog
Oct 29 14:38:34 netbox gunicorn[10161]: DEBUG:paramiko.transport:Trying discovered key b'xxxxxxxxxxxx' in /opt/netbox/.ssh/id_rsa
Oct 29 14:38:34 netbox gunicorn[10161]: DEBUG:paramiko.transport:userauth is OK
Oct 29 14:38:34 netbox gunicorn[10161]: DEBUG:paramiko.transport:Finalizing pubkey algorithm for key of type 'ssh-rsa'
Oct 29 14:38:34 netbox gunicorn[10161]: DEBUG:paramiko.transport:Our pubkey algorithm list: ['rsa-sha2-512', 'rsa-sha2-256', 'ssh-rsa']
Oct 29 14:38:34 netbox gunicorn[10161]: DEBUG:paramiko.transport:Server did not send a server-sig-algs list; defaulting to our first preferred algo ('rsa-sha2-512')Oct 29 14:38:34 netbox gunicorn[10161]: DEBUG:paramiko.transport:NOTE: you may use the 'disabled_algorithms' SSHClient/Transport init kwarg to disable that or other algorithms if your server does not support them!
Oct 29 14:38:34 netbox gunicorn[10161]: INFO:paramiko.transport:Authentication (publickey) failed.
Oct 29 14:38:34 netbox gunicorn[10161]: INFO:paramiko.transport:Disconnect (code 2):
```

**Comment by luqasz** [comment]
Does login to that MikroTik with regular ssh + key file work ?
Please execute following code and paste the output:
```python3
import logging
import paramiko
logging.basicConfig()
logging.getLogger("paramiko").setLevel(logging.DEBUG)
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(hostname='ADDRESS', username='USERNAME', allow_agent=False, key_filename='PATH_TO_YOUR_KEY')
```

I've just tried that on ROS 7.4 and logged in without any problems:
```
DEBUG:paramiko.transport:Got EXT_INFO: {'server-sig-algs': b'rsa-sha2-256,ssh-rsa'}
```

**Comment by alryaz** [comment]
Please note that the ticket describes the issue with ROS 6.40.9.

**Comment by alryaz** [comment]
Please, review https://github.com/napalm-automation-community/napalm-ros/pull/108. It might give more clarity to the problem I am trying to circumvent.

_P.S. Unfortunately, updating ROS is not an option in the foreseeable future._
