### ISSUE TITLE
Method get_environment() doesn't work on RoS 6.49.7 (RB4011iGS+)

### ISSUE THREAD

**Issue by arxsab** [napalm-automation-community/napalm-ros#112]
### napalm-ros version
(Paste verbatim output from `pip freeze | grep napalm-ros` between quotes below)

```
napalm-ros==1.2.2
```

### ROS version
(Paste verbatim output from `/system package print` between quotes below)

```
 #   NAME                   VERSION                  SCHEDULED              
 0   ntp                    6.49.7                                          
 1   routeros-arm           6.49.7                                          
 2   system                 6.49.7                                          
 3 X ipv6                   6.49.7                                          
 4   wireless               6.49.7                                          
 5   hotspot                6.49.7                                          
 6   mpls                   6.49.7                                          
 7   routing                6.49.7                                          
 8   ppp                    6.49.7                                          
 9   dhcp                   6.49.7                                          
10   security               6.49.7                                          
11   advanced-tools         6.49.7           
```

### librouteros version
(Paste verbatim output from `pip freeze | grep librouteros` between quotes below)
```
librouteros==3.2.1
```

### python version
(paste output of python --version)
```
Python 3.9.2
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
    print(device.get_environment())
  File ".local/lib/python3.9/site-packages/napalm_ros/ros.py", line 322, in get_environment
    if 'temperature' in entry['name']:
KeyError: 'name'

```

I think this is due to the fact that now the output of the command "/system health print" now is not in the form of a table/array.

**Comment by luqasz** [comment]
What does `/system health print` shows ?

**Comment by arxsab** [comment]
![image](https://user-images.githubusercontent.com/72609348/215439298-cafce376-1c03-4ce2-8a01-2f3e8cb4853e.png)


I tried to fix method rude and wrong:
`        for entry in self.api('/system/health/print'):
            if 'temperature' in entry:
                temperature = float(entry['temperature'])
                environment['temperature'] = {'temperature': temperature, 'is_alert': False, 'is_critical': False}
            if 'voltage' in entry:
                output = float(entry['voltage'])
                if int(entry['voltage']) > 0:
                    status = 'ok'
                environment['power'] = {'status': status, 'capacity': 0.0, 'output': output}
            if 'speed' in entry:
                status = (int(entry['speed']) > 50)
                environment['fans'] = {'status': status}          `
                
                and can get value:
             `{'fans': {}, 'temperature': {'temperature': 37.0, 'is_alert': False, 'is_critical': False}, 'power': {'status': 'ok', 'capacity': 0.0, 'output': 24.0}, 'cpu': {'cpu0': {'%usage': 5.0}, 'cpu1': {'%usage': 2.0}, 'cpu2': {'%usage': 4.0}, 'cpu3': {'%usage': 1.0}}, 'memory': {'available_ram': 1073741824, 'used_ram': 120836096}}
`
But the netbox could not parse these values. I understand that this question is not for you... But maybe you can correct the original mistake correctly.
![image](https://user-images.githubusercontent.com/72609348/215441907-2afa0b66-02c3-4914-8e61-8af2cecc8043.png)

**Comment by luqasz** [comment]
I am confused. Seems like MikroTik [changed](https://help.mikrotik.com/docs/display/ROS/Health) how `/system/health` is shown in 7.x. 
Can you please paste output of `/system/health/print detail` ?
I don't have any device with 7.x to test this. If you have one than please also paste same output but from 7.x.

**Comment by arxsab** [comment]
I also do not have a device with ros 7.x)
My version of routers - 6.49.7

**Comment by luqasz** [comment]
Does other devices (different models) show same output in `/system/health` ?

**Comment by arxsab** [comment]
CRS326-24G-2S+ (Ros 6.49.2)
![image](https://user-images.githubusercontent.com/72609348/218492754-b7a6a0d8-12a1-4bf5-bc11-c5a7abf394d4.png)

wAP G-5HacT2HnD (Ros 6.49.2)
![image](https://user-images.githubusercontent.com/72609348/218493176-1e88959a-efa6-4ea0-b516-9d69b0985f8a.png)

RB4011iGS+5HacQ2HnD (Ros 6.49.6)
![image](https://user-images.githubusercontent.com/72609348/218493753-87a8fbf7-b81e-43ec-b570-4c00faf77ab3.png)

**Comment by luqasz** [comment]
One last request. What does show `/system/health/print detail` ? I'd like to know if e.g. `voltage` is the key and `35.7V` is the value. Seems that on 6.x `/system/health` is totally different than on 7.x.

**Comment by arxsab** [comment]
no detailed key in ros6. I can only "print"
![image](https://user-images.githubusercontent.com/72609348/218760171-93110dd9-18b4-40a9-bd42-cd69b034c376.png)

I tried to write the output to a file and as-vaule, it is unlikely to help, but here is what it writes to the file:
/system health print file=sys-health-print.txt
[sys-health-print.txt](https://github.com/napalm-automation-community/napalm-ros/files/10733122/sys-health-print.txt)

:put [:pick {[/system health print as-value]}]
![image](https://user-images.githubusercontent.com/72609348/218764180-8742c070-6550-4247-a674-d8838cbb87c5.png)

**Comment by luqasz** [comment]
Thx for info. I will fix it, but it requires to detect which version is running on device.

**Comment by luqasz** [comment]
I need `/system/resource/cpu/print` output as well.
Created separate branch for this issue `health_check_v6`

**Comment by luqasz** [comment]
@arxsab please check/test if changes in `health_check_v6` works for you and let me know.

**Comment by arxsab** [comment]
![image](https://user-images.githubusercontent.com/72609348/220065621-7e38c502-05bf-4d50-9cb5-5f08a4ce583a.png)
Tried on Python 3.8.7 and 3.9.2 same error

**Comment by arxsab** [comment]
![image](https://user-images.githubusercontent.com/72609348/220149971-4627bbb6-818e-4795-8e78-d0108405b35f.png)
same error on python 3.8

**Comment by luqasz** [comment]
Post full text.

**Comment by arxsab** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/72609348/222091247-551be468-af11-470d-9c82-cca193d693e0.jpg)

**Comment by luqasz** [comment]
@arxsab  text not image ! You can anonymize data in text as well.

**Comment by arxsab** [comment]
test.py:

```python
import napalm
from napalm_ros import ros

router_ip = 'XXX.XXX.XXX.XXX'
router_port = XXXX
router_user = 'XXX'
router_pass = 'XXX'

driver = napalm.get_network_driver('ros')
device = driver(hostname=router_ip, username=router_user, password=router_pass, optional_args = {'port': router_port})
device.open()
#print(device.get_lldp_neighbors())
print(device.get_environment())
device.close()
```

Output:

```
Traceback (most recent call last):
  File "./test.py", line 13, in <module>
    print(device.get_environment())
  File "/usr/local/lib/python3.9/dist-packages/napalm_ros-1.2.2-py3.9.egg/napalm_ros/ros.py", line 322, in get_environment
  File "/usr/local/lib/python3.9/dist-packages/napalm_ros-1.2.2-py3.9.egg/napalm_ros/ros.py", line 627, in sys_health_pre_7
AttributeError: 'int' object has no attribute 'replace'
```

**Comment by luqasz** [comment]
Try now. Although Are you 100% sure that device on which it crashes has 6.x version ?
