### ISSUE TITLE
librouteos version 3.4.0 breaks compatibility

### ISSUE THREAD

**Issue by leoparente** [napalm-automation-community/napalm-ros#135]
### Description of Issue/Question

The latest release  (3.4.0) of librouteros  changed the variable DEFAULTS to SYNC_DEFAULTS which breaks napalm-os package as it is required in : https://github.com/napalm-automation-community/napalm-ros/blob/master/napalm_ros/ros.py#L62

### napalm-ros version

```
1.2.6
```

### librouteros version
```
3.4.0
```

### python version
```
3.12.3
```

### Error Traceback

```
module 'librouteros' has no attribute 'DEFAULTS'"
```

**Comment by luqasz** [comment]
Thx. Fixed in 3.4.1. I've yanked 3.4.0.
