### ISSUE TITLE
Enhance `get_arp_table` and `get_mac_address_table` with filtering arguments

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation-community/napalm-ros#48]
See details in the parent issue napalm-automation/napalm-base#217

**Comment by brotherdust** [comment]
I ran into this myself not too long ago. Although the API change was approved for NAPALM, there's a limitation in librouteros: it doesn't accept any filter arguments with the print command. I modified librouteros to make it work, but the change broke compatibility with NAPALM, so I ended up just using librouteros by itself. =/

**Comment by luqasz** [comment]
Currently librouteros does not have any "official" query support. I am [planning ](https://github.com/luqasz/librouteros/issues/11)to add this. For now I can implement a rather crude workaround.

**Comment by luqasz** [comment]
I am confused. `napalm-base` have some pull requests but `napalm-ros` uses `napalm` which does not have this extended method.

**Comment by luqasz** [comment]
Closing since `napalm-base` does not have any filtering.
