### ISSUE TITLE
looking for owners for ros driver

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation-community/napalm-ros#57]
Hello,
community drivers are going to be maintained by the community or considered deprecated and unmaintained. For that reason we are looking for people willing to maintain this repo. Owners will have full admin rights on this repo and on its pypy package.

Pinging top contributors to see if they are interested; @inetuid @luqasz 

If you have questions/comments let me know.

Regards

**Comment by luqasz** [comment]
Does this mean that some drivers will be maintained by some "staff" ?

I am interested in maintaining this repo.

**Comment by dbarrosop** [comment]
It basically means that core drivers (nxos, nxos-ssh, ios, iosxr, junos and eos) will be officially maintained by the 'napalm-automation' group while the other drivers will be maintained by the community. As you seem to be interested I will give you full rights over this repo and to pypy (if you don't have them already) and it's all yours. You can do and undo as you please :)

We have been slowing you down due to our lack of knowledge on this platform and our limited available time so it's better if you step back and let you do as you think it's best. We can still help on specific matters if you need it but you are free :)

**Comment by dbarrosop** [comment]
Just gave you admin access.

**Comment by luqasz** [comment]
@dbarrosop What about pypi uploads ?

**Comment by dbarrosop** [comment]
What's your username on pypi? I will make you admin there.

**Comment by luqasz** [comment]
`lkostka`

**Comment by dbarrosop** [comment]
Done!
