### ISSUE TITLE
get_environment method not working. "tuple index out of range"

### ISSUE THREAD

**Issue by joaolucasmacedo** [napalm-automation-community/napalm-ros#76]
### napalm version 
"2.5.0"
### napalm-ros version 
"0.5.1"
### ROS version
6.47

![Napalm-ros error](https://user-images.githubusercontent.com/66760118/84338842-863db080-ab73-11ea-9cd4-913116312766.png)

**Comment by luqasz** [comment]
Please provide output of `/system health print` from console.

**Comment by joaolucasmacedo** [comment]
> .

It returns nothing.

**Comment by joaolucasmacedo** [comment]
<img width="471" alt="system health" src="https://user-images.githubusercontent.com/66760118/84461184-35e15400-ac42-11ea-8105-fedac358576d.png">

**Comment by luqasz** [comment]
I know why this is happening. I need to ask in `napalm-base` what to do in such case.

**Comment by joaolucasmacedo** [comment]
> 
> 
> I know why this is happening. I need to ask in `napalm-base` what to do in such case.
> 
> [napalm-automation/napalm#1238](https://github.com/napalm-automation/napalm/issues/1238)

Did you find any workaround?

**Comment by luqasz** [comment]
Yes. I will fix it today
