### ISSUE TITLE
Support for napalm version 3.*

### ISSUE THREAD

**Issue by konstanting-kaymera** [napalm-automation-community/napalm-ros#82]
Hello! 
The plugin id great! :fire: :1st_place_medal: 
Is it possible to make `napalm-ros` to work with `napalm` version 3 
right now the restriction in `setup.py:41` is `napalm==2.*`

Thank you

**Comment by luqasz** [comment]
Hi. 
Yes it is possible and I will do it.

**Comment by luqasz** [comment]
Released in version 1.0.0
